version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: del
    versions:
    - "> 5.1.0"
  - dependency-name: gulp-replace
    versions:
    - 1.1.1
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: mime
    versions:
    - 2.5.0
